"""shop contact and origin

Revision ID: 021254b34c01
Revises: df7c5c6624a5
Create Date: 2026-07-23 13:57:42.330118
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '021254b34c01'
down_revision: Union[str, None] = 'df7c5c6624a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shops', sa.Column('address', sa.String(), nullable=True))
    op.add_column('shops', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('shops', sa.Column('province', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shops', 'province')
    op.drop_column('shops', 'phone')
    op.drop_column('shops', 'address')
    # ### end Alembic commands ###
