"""variant position

Revision ID: 1a2ec436f867
Revises: bac66977e7cf
Create Date: 2026-07-23 21:04:33.562658
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a2ec436f867'
down_revision: Union[str, None] = 'bac66977e7cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills the variants that already exist; a NOT NULL
    # column with no default cannot be added to a table with rows.
    op.add_column(
        'product_variants',
        sa.Column('position', sa.Integer(), nullable=False, server_default='0'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_variants', 'position')
    # ### end Alembic commands ###
