"""shop logo

Revision ID: 6caa8868c2db
Revises: fb69c568aa96
Create Date: 2026-07-23 15:31:39.294074
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6caa8868c2db'
down_revision: Union[str, None] = 'fb69c568aa96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shops', sa.Column('logo_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shops', 'logo_url')
    # ### end Alembic commands ###
