"""product image gallery

Revision ID: 7f7f2bca6342
Revises: fe36825e9896
Create Date: 2026-07-23 14:29:54.066444
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f7f2bca6342'
down_revision: Union[str, None] = 'fe36825e9896'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_urls', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'image_urls')
    # ### end Alembic commands ###
