"""payment sessions and exceptions

Revision ID: 9e273ea45236
Revises: c4086cf5dbe9
Create Date: 2026-07-23 22:31:09.815580
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e273ea45236'
down_revision: Union[str, None] = 'c4086cf5dbe9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_exceptions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('gateway_payment_id', sa.String(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_exceptions_gateway_payment_id'), 'payment_exceptions', ['gateway_payment_id'], unique=False)
    op.create_index(op.f('ix_payment_exceptions_order_id'), 'payment_exceptions', ['order_id'], unique=False)
    op.add_column('orders', sa.Column('payment_id', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('payment_started_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'payment_started_at')
    op.drop_column('orders', 'payment_id')
    op.drop_index(op.f('ix_payment_exceptions_order_id'), table_name='payment_exceptions')
    op.drop_index(op.f('ix_payment_exceptions_gateway_payment_id'), table_name='payment_exceptions')
    op.drop_table('payment_exceptions')
    # ### end Alembic commands ###
