"""vouchers and shop order discount

Revision ID: 9ffc06c63523
Revises: 6caa8868c2db
Create Date: 2026-07-23 16:55:10.053547
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ffc06c63523'
down_revision: Union[str, None] = '6caa8868c2db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vouchers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('shop_id', sa.String(), nullable=True),
    sa.Column('discount_type', sa.String(), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('max_discount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('min_order', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.CheckConstraint("discount_type <> 'PERCENT' OR discount_value <= 100", name='ck_vouchers_percent_range'),
    sa.CheckConstraint("discount_type IN ('PERCENT', 'AMOUNT')", name='ck_vouchers_discount_type'),
    sa.CheckConstraint('discount_value > 0', name='ck_vouchers_value_positive'),
    sa.CheckConstraint('ends_at > starts_at', name='ck_vouchers_window'),
    sa.CheckConstraint('min_order >= 0', name='ck_vouchers_min_order'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vouchers_code'), 'vouchers', ['code'], unique=True)
    op.create_index(op.f('ix_vouchers_shop_id'), 'vouchers', ['shop_id'], unique=False)
    # server_default backfills the orders placed before vouchers existed —
    # a NOT NULL column with no default cannot be added to a table that
    # already has rows. Those orders had no voucher, so 0 is the truth.
    op.add_column(
        'shop_orders',
        sa.Column(
            'discount',
            sa.Numeric(precision=12, scale=2),
            nullable=False,
            server_default='0',
        ),
    )
    op.add_column('shop_orders', sa.Column('voucher_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop_orders', 'voucher_code')
    op.drop_column('shop_orders', 'discount')
    op.drop_index(op.f('ix_vouchers_shop_id'), table_name='vouchers')
    op.drop_index(op.f('ix_vouchers_code'), table_name='vouchers')
    op.drop_table('vouchers')
    # ### end Alembic commands ###
