"""order idempotency key

Revision ID: ac8f836a858d
Revises: 1a2ec436f867
Create Date: 2026-07-23 21:43:51.039217
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac8f836a858d'
down_revision: Union[str, None] = '1a2ec436f867'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('idempotency_key', sa.String(), nullable=True))
    op.create_unique_constraint('uq_orders_buyer_idempotency', 'orders', ['buyer_id', 'idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_orders_buyer_idempotency', 'orders', type_='unique')
    op.drop_column('orders', 'idempotency_key')
    # ### end Alembic commands ###
