"""order item variant snapshot

Revision ID: bac66977e7cf
Revises: c58518c9a8c9
Create Date: 2026-07-23 20:52:20.175101
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bac66977e7cf'
down_revision: Union[str, None] = 'c58518c9a8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('variant_id', sa.String(), nullable=True))
    op.add_column('order_items', sa.Column('variant_label', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'variant_label')
    op.drop_column('order_items', 'variant_id')
    # ### end Alembic commands ###
