"""product sku

Revision ID: c4086cf5dbe9
Revises: ac8f836a858d
Create Date: 2026-07-23 22:06:45.193137
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4086cf5dbe9'
down_revision: Union[str, None] = 'ac8f836a858d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('sku', sa.String(), nullable=True))
    op.create_unique_constraint('uq_products_shop_sku', 'products', ['shop_id', 'sku'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_products_shop_sku', 'products', type_='unique')
    op.drop_column('products', 'sku')
    # ### end Alembic commands ###
