"""voucher category rule

Revision ID: ef4615ba726e
Revises: 9ffc06c63523
Create Date: 2026-07-23 17:12:30.277545
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef4615ba726e'
down_revision: Union[str, None] = '9ffc06c63523'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vouchers', sa.Column('category', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vouchers', 'category')
    # ### end Alembic commands ###
