"""product category

Revision ID: fb69c568aa96
Revises: 7f7f2bca6342
Create Date: 2026-07-23 14:57:54.192325
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb69c568aa96'
down_revision: Union[str, None] = '7f7f2bca6342'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('category', sa.String(), nullable=True))
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_column('products', 'category')
    # ### end Alembic commands ###
